spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
  datasource:
    url: jdbc:ignite:thin://localhost:10800
    driver-class-name: org.apache.ignite.IgniteJdbcThinDriver
  session:
    store-type: jdbc